In [2]:
from sklearn import datasets
iris=datasets.load_iris()
x=iris.data
y=iris.target
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_std = sc.fit_transform(x)
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test)=train_test_split(x_std,y,test_size=0.3)

C:\Users\Akash\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 2)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [5]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(y_test,y_pred)
print(acc)
cf=classification_report(y_test,y_pred)
print(cf)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.9333333333333333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.82      1.00      0.90        14
           2       1.00      0.83      0.91        18

    accuracy                           0.93        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.95      0.93      0.93        45

[[13  0  0]
 [ 0 14  0]
 [ 0  3 15]]
