In [3]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer


In [4]:
df = pd.read_csv("file2.csv")
print(df)#dataframe

      A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN


In [10]:
imr = SimpleImputer(missing_values=np.nan,strategy='mean')
# strategy = mean, median, most_frequent
imr = imr.fit(df)
imputed_data = imr.transform(df.values)
print(imputed_data)

[[10.         20.         30.         40.        ]
 [ 1.          2.         21.          4.        ]
 [ 5.          6.         21.          8.        ]
 [ 0.         11.         12.         17.33333333]]


In [6]:
imr = SimpleImputer(missing_values=np.nan,strategy='median')
# strategy = mean, median, mode, most_frequent
imr = imr.fit(df)
imputed_data = imr.transform(df.values)
print(imputed_data)

[[10. 20. 30. 40.]
 [ 1.  2. 21.  4.]
 [ 5.  6. 21.  8.]
 [ 0. 11. 12.  8.]]


In [8]:
imr = SimpleImputer(missing_values=np.nan,strategy='most_frequent')
# strategy = mean, median, mode, most_frequent
imr = imr.fit(df)
imputed_data = imr.transform(df.values)
print(imputed_data)

[[10. 20. 30. 40.]
 [ 1.  2. 12.  4.]
 [ 5.  6. 12.  8.]
 [ 0. 11. 12.  4.]]


In [9]:
df

A     B     C     D
0  10.0  20.0  30.0  40.0
1   1.0   2.0   NaN   4.0
2   5.0   6.0   NaN   8.0
3   0.0  11.0  12.0   NaN

### Mapping

In [11]:
data = pd.read_csv("file3.csv")
print(data)

   Color Size  Price Classlabel
0    Red    L  15.10     Class1
1  Green   XL  20.00     Class2
2   Blue    S  12.34     Class2
3    Red    M  13.00     Class1


In [32]:
size_mapping = {"XS":0, "S":1,"M":2, "L":3,"XL":4, "XXL":5}
data1 = data.replace(size_mapping)
print(data1)

   Color Size  Price Classlabel
0    Red    3  15.10     Class1
1  Green    4  20.00     Class2
2   Blue    1  12.34     Class2
3    Red    2  13.00     Class1


In [23]:
class_mapping = {"Class1":0, "Class2":1, "Class2":2}
data2 = data.replace(class_mapping)
print(data2)

   Color Size  Price  Classlabel
0    Red    L  15.10           0
1  Green   XL  20.00           2
2   Blue    S  12.34           2
3    Red    M  13.00           0


### inverse mapping

In [37]:
inverse_size_mapping = {v:k for k,v in size_mapping.items()}
print(data1)
data1 = data1.replace(inverse_size_mapping)
#data1 = data1["Size"].replace(inverse_size_mapping)    when we need to change data at particular column
print(data1)

   Color Size  Price Classlabel
0    Red    L  15.10     Class1
1  Green   XL  20.00     Class2
2   Blue    S  12.34     Class2
3    Red    M  13.00     Class1 



   Color Size  Price Classlabel
0    Red    L  15.10     Class1
1  Green   XL  20.00     Class2
2   Blue    S  12.34     Class2
3    Red    M  13.00     Class1


In [47]:
data3 = data1["Size"].replace(inverse_size_mapping)
data3

0     L
1    XL
2     S
3     M
Name: Size, dtype: object

### Concatenation

In [48]:
data4 = pd.concat([data1[["Classlabel", "Color", "Price"]],data3],axis = 1)
data4

Classlabel  Color  Price Size
0     Class1    Red  15.10    L
1     Class2  Green  20.00   XL
2     Class2   Blue  12.34    S
3     Class1    Red  13.00    M

In [49]:
data

Color Size  Price Classlabel
0    Red    L  15.10     Class1
1  Green   XL  20.00     Class2
2   Blue    S  12.34     Class2
3    Red    M  13.00     Class1

### Map Classlabel in 1 and 2 numeric values using label encoder and vice versa
### Transform all values color, size and Classlabel in numeric using label encoder 

In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(data["Size"].values)
print(y)

z = le.inverse_transform(y)
print(z)

[0 3 2 1]
['L' 'XL' 'S' 'M']


In [60]:
X = data.values
print(X,"\n\n")
X[:,0] = le.fit_transform(X[:,0])
print(X, "\n\n")

X[:,1] = le.fit_transform(X[:,1])
print(X,"\n\n")

#price colum is already transformed

X[:,3] = le.fit_transform(X[:,3])
print(X)

[['Red' 'L' 15.1 'Class1']
 ['Green' 'XL' 20.0 'Class2']
 ['Blue' 'S' 12.34 'Class2']
 ['Red' 'M' 13.0 'Class1']] 


[[2 'L' 15.1 'Class1']
 [1 'XL' 20.0 'Class2']
 [0 'S' 12.34 'Class2']
 [2 'M' 13.0 'Class1']] 


[[2 0 15.1 'Class1']
 [1 3 20.0 'Class2']
 [0 2 12.34 'Class2']
 [2 1 13.0 'Class1']] 


[[2 0 15.1 0]
 [1 3 20.0 1]
 [0 2 12.34 1]
 [2 1 13.0 0]]


## One Hot Encoding

In [72]:
country_data = pd.DataFrame({"Country":["RUS", "GER","IND", "PAK","AUS", "IND","IND", "AUS","AUS", "RUS"]})
country_data

Country
0     RUS
1     GER
2     IND
3     PAK
4     AUS
5     IND
6     IND
7     AUS
8     AUS
9     RUS

In [78]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
country_data1 = le.fit_transform(country_data.values)#using normal encoding
print(country_data1)

[4 1 2 3 0 2 2 0 0 4]


In [79]:
country_data2 = pd.get_dummies(country_data, prefix=["Country"])
print(country_data2)

   Country_AUS  Country_GER  Country_IND  Country_PAK  Country_RUS
0            0            0            0            0            1
1            0            1            0            0            0
2            0            0            1            0            0
3            0            0            0            1            0
4            1            0            0            0            0
5            0            0            1            0            0
6            0            0            1            0            0
7            1            0            0            0            0
8            1            0            0            0            0
9            0            0            0            0            1


In [86]:
from sklearn.preprocessing import OneHotEncoder
oe = OneHotEncoder()
country_data3 = oe.fit_transform(country_data)
print(country_data3.toarray(),"\n\n")
country_data4 = pd.DataFrame(country_data3.toarray(), columns = ["A", "B", "C", "D", "E"])
print(country_data4)

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]] 


     A    B    C    D    E
0  0.0  0.0  0.0  0.0  1.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  1.0  0.0  0.0  0.0  0.0
5  0.0  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0  0.0
7  1.0  0.0  0.0  0.0  0.0
8  1.0  0.0  0.0  0.0  0.0
9  0.0  0.0  0.0  0.0  1.0


In [88]:
new_data = pd.DataFrame({"Name":["A", "B", "C", "D"],"Country":["RUS", "GER","IND","AUS"]})
print(new_data)

  Name Country
0    A     RUS
1    B     GER
2    C     IND
3    D     AUS


In [94]:
new_data1 = pd.concat([new_data,pd.get_dummies(new_data["Country"], prefix = "Country")],axis=1)
new_data1

Name Country  Country_AUS  Country_GER  Country_IND  Country_RUS
0    A     RUS            0            0            0            1
1    B     GER            0            1            0            0
2    C     IND            0            0            1            0
3    D     AUS            1            0            0            0

In [97]:
new_data2 = new_data1.drop("Country", axis=1)
print(new_data2)

  Name  Country_AUS  Country_GER  Country_IND  Country_RUS
0    A            0            0            0            1
1    B            0            1            0            0
2    C            0            0            1            0
3    D            1            0            0            0
