In [2]:
from sklearn import datasets
iris=datasets.load_iris()
x=iris.data
y=iris.target
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_std = sc.fit_transform(x)
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test)=train_test_split(x_std,y,test_size=0.3)

C:\Users\Akash\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)


In [4]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
acc=accuracy_score(y_test,y_pred)
print(acc)
cf=classification_report(y_test,y_pred)
print(cf)
cm=confusion_matrix(y_test,y_pred)
print(cm)

0.9555555555555556
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.92      0.92      0.92        13
           2       0.95      0.95      0.95        19

    accuracy                           0.96        45
   macro avg       0.96      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

[[13  0  0]
 [ 0 12  1]
 [ 0  1 18]]
